### ISSUE TITLE
Rework the way missing files are treated

### ISSUE THREAD

**Issue by boi123212321** [porn-vault/porn-vault#320] opened 2020-02-15 23:48 UTC
Instead of removing file references from scenes and deleting images when using REMOVE_DANGLING_FILE_REFERENCES, provide a list of "critical" scenes & images, where the user has the final say which files to delete etc.

**Comment by echo6ix** [comment] 2020-05-05 18:05
You could add something like a `Clean Up` subsection to the settings page re: #524 with a button for on-demand cleaning of missing files and any associated app created files (thumbnails, previews, etc). 

Like the screenshot, the option opens a modal window warning the user that any references and items to the missing files will be removed, and it is not a reversible action.

![Annotation 2020-05-05 135930](https://user-images.githubusercontent.com/37937507/81099293-ae812200-8ed8-11ea-8128-2225b0b1073f.jpg)

If users have to sort through a list of all missing items before confirming deletion that might be a pita in instances where someone changes or deletes directories containing hundreds of images.

**Comment by echo6ix** [comment] 2020-05-05 18:10
If I understand correctly, the motivation for providing a list of missing files to confirm removal is for dropped NAS sources. Instead of showing a list of files to be confirmed, what about a warning to the user that the root source specified in config.json cannot be found?

**Comment by boi123212321** [comment] 2020-05-29 12:08
https://github.com/boi123212321/porn-vault/pull/607

**Comment by leadwolf** [comment] 2021-03-29 23:48
Transferred from #1366

> Is your feature request related to a problem? Please describe.
I have renamed a bunch of folders, now there are many duplicate entries, and the old ones don't work any more because the file is no longer at the old location.
>
> Describe the solution you'd like
A "check if all files are still present and ask whether the scenes should be deleted" button would be nice

**Closed** 2021-05-20 12:02 UTC
Labels: api, enhancement, epic, new feature
