### ISSUE TITLE
Encode filters into URL

### ISSUE THREAD

**Issue by Timat123** [porn-vault/porn-vault#1086] opened 2020-12-08 02:23 UTC
**Describe the bug**
Different tabs share filter state

**To Reproduce**
1. Open 2 tabs
2. Create filter in one
3. Observe the other

**Expected behavior**
It doesn't to that.

**Desktop (please complete the following information):**
 - OS: W10
 - Browser: Firefox
 - Version: 83

**Comment by boi123212321** [comment] 2020-12-08 13:48
Everything is stored in localStorage.
On the one hand, it does allow persistent sessions, on the other hand it causes that kind of issue.
The server doesn't really have sessions, so currently it can't store and retrieve stuff from the database, that's why it uses localStorage.

**Comment by leadwolf** [comment] 2020-12-08 13:59
I don't think it'd work even with sessions since sessions are shared between tabs

**Comment by boi123212321** [comment] 2020-12-08 14:20
@leadwolf Using sessionStorage, every tab is a new session

**Comment by leadwolf** [comment] 2020-12-08 14:25
OK. But I can't think of any way to only have the data "restored" when opening the app for the first time, but not when opening a second tab alongside

**Comment by boi123212321** [comment] 2020-12-08 14:29
Me neither, every tab would need to get a session and store options server-side, which i don't feel like doing as long as i'm not using some sort of server side rendered framework

**Comment by leadwolf** [comment] 2020-12-08 18:26
Personally, I don't think there's a huge benefit to putting a ton of work into it, since the problem is only if you open/refresh the 2nd tab after having made changes in the 1st. I don't see why you'd refresh the page in the 2nd tab anyways.

**Comment by Timat123** [comment] 2020-12-08 23:32
Why do you want to restore state which is not encoded in the url? If you implement #1087 this will get even worse, you will click on links which were created with different filters and nothing will match up.

>I don't see why you'd refresh the page in the 2nd tab anyways.

What exactly do you mean with refreshing? This is definitely broken by normal usage:
- navigate to scenes page 2 in tab1
- create filter in tab2
- go to actors page in tab1
- go to views page in tab1

Now I still am on page2, but there is no page 2 because of the filter and I can't even go back to page 1 because the buttons are not being displayed:
![image](https://user-images.githubusercontent.com/75649683/101552600-64eb3f00-39b3-11eb-920c-16af32aa56ed.png)

With all sincerity, you should not abuse the localStorage to track UI state. Page numbers, search queries and the like should go into the url, so that we can send links which produce the same content. If the rendered content depends on your localStorage content, you will never have reliable links to your page.

Also please don't forget that localStorage is being accessed [concurrently by the js event loops of different tabs](https://balpha.de/2012/03/javascript-concurrency-and-locking-the-html5-localstorage/). If your code assumes that the data in there is stable, you will have inconsistencies like I have reproduced.

**Comment by leadwolf** [comment] 2020-12-08 23:54
OK. I see what you mean. But the problem can simply be resolved by reading from localStorage only on the mount of the app and not when mounting different pages. Saving to localStorage allows you to close all tabs, but come back and still have your filters saved, without having to reopen a specific url. The data saved could also include pagination.  
But I don't think this would conflict with filters in the url. Applying filters could be done in two steps:
- use any filters from the url
- use filters saved in localStorage

In any case, the current state can be still saved to localStorage as it changes (as it is now).  

About localStorage only being synchronous, that is not a problem since it should (is) only be used to restore state and not communicate between different components.

**Comment by Timat123** [comment] 2020-12-09 00:01
This way you'd have to take care of the decoding twice, though. Do you really think you users' filters are so complex that they definitely always want all of them back when they return? I usually have several tabs open and don't even know which have which filter applied.

>I don't think latency is a problem either, since state changes can only be triggered by user interaction and I don't think users are racing to apply filters in multiple tabs at the same time.

The latency won't be, but code like in the scenes page that has false assumptions about its saved state is :(

**Comment by leadwolf** [comment] 2020-12-09 00:07
The filters don't have to be complex. I appreciate not having to retype or select filters and then execute the search to come back to what I was looking at last time

**Comment by Timat123** [comment] 2020-12-09 00:18
Nevertheless, if you want that everyone sees the same content when opening a link in #1087, nothing outside of that link must influence what is being displayed. Maybe only load the saved filters when navigating to /?

**Comment by boi123212321** [comment] 2020-12-09 00:20
> Maybe only load the saved filters when navigating to /?

> But the problem can simply be resolved by reading from localStorage only on the mount of the app and not when mounting different pages

**Comment by Timat123** [comment] 2020-12-09 00:26
Doesn't a mount happen when you click on a non-relative link like http://foobar/actors?

**Comment by boi123212321** [comment] 2020-12-09 00:31
App mount only happens once, every time you open the web app in a tab, or press F5

**Comment by Timat123** [comment] 2020-12-09 00:33
So someone who clicks on a link I sent will see different things, depending on our filters, won't he?

**Comment by leadwolf** [comment] 2020-12-09 00:48
Not if the link already contains filters

**Comment by Timat123** [comment] 2020-12-09 01:09
Ah so if you detect that the url declares filters (or the absence of them) you'd use that, and only fall back to localStorage if the url does not? 👍

**Closed** 2021-02-14 13:48 UTC
Labels: enhancement, help wanted/open for pr
