### ISSUE TITLE
[Feature] <Clean up dead entries>

### ISSUE THREAD

**Issue by dnizmirc** [porn-vault/porn-vault#1539] opened 2021-06-05 18:07 UTC
**Is your feature request related to a problem? Please describe.**
If I move or rename files, PV leaves a dead-entry for the now "missing" file and creates a "new" one for the "new" entry.

**Describe the solution you'd like**
I know some people use non-always-present storage, and automatically removing entries would cause problems for them. I'd like an option, maybe tucked in the settings, to remove lost/missing files.

(slightly paired with a different request. If I could rename/move files through PV, I wouldn't need to manually update actual files myself, PV wouldn't get confused, etc)

**Comment by boi123212321** [comment] 2021-06-05 18:46
You can change the file path of scenes.

Rest is duplicate of https://github.com/porn-vault/porn-vault/discussions/1492

**Closed by boi123212321** 2021-06-05 18:46 UTC
Labels: new feature
