### ISSUE TITLE
[Feature] Bulk remove deleted files

### ISSUE THREAD

**Issue by Timat123** [porn-vault/porn-vault#1366] opened 2021-03-29 14:51 UTC
**Is your feature request related to a problem? Please describe.**
I have renamed a bunch of folders, now there are many duplicate entries, and the old ones don't work any more because the file is no longer at the old location.

**Describe the solution you'd like**
A "check if all files are still present and ask whether the scenes should be deleted" button would be nice

**Comment by leadwolf** [comment] 2021-03-29 23:47
Duplicate of #320 although I will copy your concerns

**Closed by leadwolf** 2021-03-29 23:47 UTC
Labels: new feature

**Comment by Timat123** [comment] 2022-01-02 23:18
Your link to #320 404s, are there any news?
